# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'liamgu/simpleapp'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    pool:
      vmImage: ubuntu-latest
      
    steps:
    - task: Docker@2
      displayName: 'docker build'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '$(System.DefaultWorkingDirectory)/src/simpleApp/Dockerfile'
        tags: '$(Build.BuildNumber)'

    - task: Docker@2
      displayName: 'docker push'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageName)'
        command: 'push'
        tags: '$(Build.BuildNumber)'