trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'liamgu/simpleapp'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    pool:
      vmImage: ubuntu-latest
      
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '$(System.DefaultWorkingDirectory)/src/simpleApp/Dockerfile'
        tags: |
          $(Build.BuildNumber)
          latest
