trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'liamgu/simpleapp'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    pool:
      vmImage: ubuntu-latest
      
    steps:
    - task: Docker@2
      displayName: 'docker build'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '$(System.DefaultWorkingDirectory)/src/simpleApp/Dockerfile'
        tags: |
          $(Build.BuildNumber)
          latest

    - task: Docker@2
      displayName: 'docker push'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageName)'
        command: 'push'
        tags: '$(Build.BuildNumber)'

- stage: Dev
  dependsOn: Build
  displayName: Dev

  variables:
    environment_name: dev
    siteName: lgdonedemo    
  
  jobs:  
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
  
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Bicep'
      inputs:
        azureSubscription: 'VS Sub'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create -l uksouth -n lg-done-$(environment_name)-rg
          az deployment group create -f $(System.DefaultWorkingDirectory)/infrastructure/webapp-for-containers.bicep -g lg-done-$(environment_name)-rg --parameters siteName=$(siteName)-$(environment_name)
        addSpnToEnvironment: true
    
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy simpleapp:$(Build.BuildNumber)'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'VS Sub'
        appType: 'webAppContainer'
        WebAppName: '$(siteName)-$(environment_name)'
        DockerNamespace: 'liamgu'
        DockerRepository: 'simpleapp'
        DockerImageTag: '$(Build.BuildNumber)'
